# Generated by Django 6.0.3 on 2026-04-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
